### ISSUE TITLE
cda-core-2.0 failing to build due to heap space issues

### ISSUE THREAD

**Issue by seanmcilvenna** [HL7/cda-ccda-2.2#15]
```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3746)
	at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:172)
	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:538)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:174)
	at org.hl7.fhir.igtools.renderers.StructureDefinitionRenderer.generateReplacements(StructureDefinitionRenderer.java:702)
	at org.hl7.fhir.igtools.renderers.StructureDefinitionRenderer.dict(StructureDefinitionRenderer.java:665)
	at org.hl7.fhir.igtools.publisher.Publisher.generateOutputsStructureDefinition(Publisher.java:5919)
	at org.hl7.fhir.igtools.publisher.Publisher.generateHtmlOutputs(Publisher.java:5263)
	at org.hl7.fhir.igtools.publisher.Publisher.generate(Publisher.java:3876)
	at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:735)
	at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:612)
	at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:6453)
```

**Comment by seanmcilvenna** [comment]
This PR https://github.com/HL7/cda-core-2.0/pull/13 seems to have fixed the problem.
